name: Build OLA Firmware

on:
  # This is a called workflow
  workflow_call:
    outputs:
      build-file:
        description: "The output of this build procsss"
        value: ${{ jobs.build.outputs.binary-file }}

env:
  FILENAME_PREFIX: OpenLog_Artemis_GNSS_Logging

jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest

    # Output
    outputs:
      binary-file: ${{ steps.output-binary.outputs.filename }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get firmware version
        id: firmwareVersion
        run: |
          echo "firmwareMajor=$(grep -Po "(?<=FIRMWARE_VERSION_MAJOR = )([0-9])*(?=;$)" ./Firmware/${{ env.FILENAME_PREFIX }}/${{ env.FILENAME_PREFIX }}.ino)" >> "$GITHUB_ENV"
          echo "firmwareMinor=$(grep -Po "(?<=FIRMWARE_VERSION_MINOR = )([0-9])*(?=;$)" ./Firmware/${{ env.FILENAME_PREFIX }}/${{ env.FILENAME_PREFIX }}.ino)" >> "$GITHUB_ENV"
          echo "firmwareMajorMinor=-V10-v${{ env.firmwareMajor }}${{ env.firmwareMinor }}" >> $GITHUB_OUTPUT

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Start config file
        run: arduino-cli config init --additional-urls "https://raw.githubusercontent.com/sparkfun/Arduino_Apollo3/main/package_sparkfun_apollo3_index.json"

      - name: Update index
        run: arduino-cli core update-index

      - name: Install platform
        run: arduino-cli core install "Sparkfun:apollo3@2.2.1"

      - name: Get Known Libraries
        run: arduino-cli lib install
          "SparkFun u-blox GNSS v3"@3.1.2
          "SdFat@2.2.2"

      - name: Patch Apollo3 Core
        run: |
          cd ./Extras
          unzip UartPower3.zip
          cp HardwareSerial.h /home/runner/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-extend/HardwareSerial.h
          cp HardwareSerial.cpp /home/runner/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-implement/HardwareSerial.cpp
          cp UnbufferedSerial.h /home/runner/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/drivers/UnbufferedSerial.h
          cp serial_api.c /home/runner/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/serial_api.c
          cp libmbed-os.a /home/runner/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/variants/SFE_ARTEMIS_ATP/mbed/libmbed-os.a
          cd /home/runner/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/libraries/SPI
          patch -p1 ./Extras/spi.diff

      - name: Compile Sketch
        run: arduino-cli compile -v -e -b SparkFun:apollo3:sfe_artemis_atp ./Firmware/${{ env.FILENAME_PREFIX }}/${{ env.FILENAME_PREFIX }}.ino

      - name: Rename binary
        run: |
          cd ./Firmware/${{ env.FILENAME_PREFIX }}
          mv ${{ env.FILENAME_PREFIX }}.ino.bin ${{ env.FILENAME_PREFIX }}${{ steps.firmwareVersion.outputs.firmwareMajorMinor }}.bin

      - name: Upload binary to action
        uses: actions/upload-artifact@v3
        with: 
          name: ${{ env.FILENAME_PREFIX }}${{ steps.firmwareVersion.outputs.firmwareMajorMinor }}.bin
          path: ./Firmware/${{ env.FILENAME_PREFIX }}/${{ env.FILENAME_PREFIX }}${{ steps.firmwareVersion.outputs.firmwareMajorMinor }}.bin

      - name: Output binary
        id: output-binary
        run: echo "filename=RTKUploader.linux.gz" >> $GITHUB_OUTPUT