# Workflow that builds the firmware, but doesn't add to a release.

name: non-release-build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: 

jobs:
  # Build the firmware
  call-compile-firmware:
    uses: ./.github/workflows/compile-firmware.yml
